/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginLayoutRouteRouteImport } from './routes/_loginLayout/route'
import { Route as AuthedLayoutRouteRouteImport } from './routes/_authedLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginLayoutSignUpIndexRouteImport } from './routes/_loginLayout/signUp/index'
import { Route as LoginLayoutFindPwIndexRouteImport } from './routes/_loginLayout/findPw/index'
import { Route as LoginLayoutFindIdIndexRouteImport } from './routes/_loginLayout/findId/index'
import { Route as AuthedLayoutAboutIndexRouteImport } from './routes/_authedLayout/about/index'

const LoginLayoutRouteRoute = LoginLayoutRouteRouteImport.update({
  id: '/_loginLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutRouteRoute = AuthedLayoutRouteRouteImport.update({
  id: '/_authedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLayoutSignUpIndexRoute = LoginLayoutSignUpIndexRouteImport.update({
  id: '/signUp/',
  path: '/signUp/',
  getParentRoute: () => LoginLayoutRouteRoute,
} as any)
const LoginLayoutFindPwIndexRoute = LoginLayoutFindPwIndexRouteImport.update({
  id: '/findPw/',
  path: '/findPw/',
  getParentRoute: () => LoginLayoutRouteRoute,
} as any)
const LoginLayoutFindIdIndexRoute = LoginLayoutFindIdIndexRouteImport.update({
  id: '/findId/',
  path: '/findId/',
  getParentRoute: () => LoginLayoutRouteRoute,
} as any)
const AuthedLayoutAboutIndexRoute = AuthedLayoutAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AuthedLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/about': typeof AuthedLayoutAboutIndexRoute
  '/findId': typeof LoginLayoutFindIdIndexRoute
  '/findPw': typeof LoginLayoutFindPwIndexRoute
  '/signUp': typeof LoginLayoutSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/about': typeof AuthedLayoutAboutIndexRoute
  '/findId': typeof LoginLayoutFindIdIndexRoute
  '/findPw': typeof LoginLayoutFindPwIndexRoute
  '/signUp': typeof LoginLayoutSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authedLayout': typeof AuthedLayoutRouteRouteWithChildren
  '/_loginLayout': typeof LoginLayoutRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authedLayout/about/': typeof AuthedLayoutAboutIndexRoute
  '/_loginLayout/findId/': typeof LoginLayoutFindIdIndexRoute
  '/_loginLayout/findPw/': typeof LoginLayoutFindPwIndexRoute
  '/_loginLayout/signUp/': typeof LoginLayoutSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/about' | '/findId' | '/findPw' | '/signUp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/about' | '/findId' | '/findPw' | '/signUp'
  id:
    | '__root__'
    | '/'
    | '/_authedLayout'
    | '/_loginLayout'
    | '/login/'
    | '/_authedLayout/about/'
    | '/_loginLayout/findId/'
    | '/_loginLayout/findPw/'
    | '/_loginLayout/signUp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedLayoutRouteRoute: typeof AuthedLayoutRouteRouteWithChildren
  LoginLayoutRouteRoute: typeof LoginLayoutRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_loginLayout': {
      id: '/_loginLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LoginLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authedLayout': {
      id: '/_authedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_loginLayout/signUp/': {
      id: '/_loginLayout/signUp/'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof LoginLayoutSignUpIndexRouteImport
      parentRoute: typeof LoginLayoutRouteRoute
    }
    '/_loginLayout/findPw/': {
      id: '/_loginLayout/findPw/'
      path: '/findPw'
      fullPath: '/findPw'
      preLoaderRoute: typeof LoginLayoutFindPwIndexRouteImport
      parentRoute: typeof LoginLayoutRouteRoute
    }
    '/_loginLayout/findId/': {
      id: '/_loginLayout/findId/'
      path: '/findId'
      fullPath: '/findId'
      preLoaderRoute: typeof LoginLayoutFindIdIndexRouteImport
      parentRoute: typeof LoginLayoutRouteRoute
    }
    '/_authedLayout/about/': {
      id: '/_authedLayout/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthedLayoutAboutIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
  }
}

interface AuthedLayoutRouteRouteChildren {
  AuthedLayoutAboutIndexRoute: typeof AuthedLayoutAboutIndexRoute
}

const AuthedLayoutRouteRouteChildren: AuthedLayoutRouteRouteChildren = {
  AuthedLayoutAboutIndexRoute: AuthedLayoutAboutIndexRoute,
}

const AuthedLayoutRouteRouteWithChildren =
  AuthedLayoutRouteRoute._addFileChildren(AuthedLayoutRouteRouteChildren)

interface LoginLayoutRouteRouteChildren {
  LoginLayoutFindIdIndexRoute: typeof LoginLayoutFindIdIndexRoute
  LoginLayoutFindPwIndexRoute: typeof LoginLayoutFindPwIndexRoute
  LoginLayoutSignUpIndexRoute: typeof LoginLayoutSignUpIndexRoute
}

const LoginLayoutRouteRouteChildren: LoginLayoutRouteRouteChildren = {
  LoginLayoutFindIdIndexRoute: LoginLayoutFindIdIndexRoute,
  LoginLayoutFindPwIndexRoute: LoginLayoutFindPwIndexRoute,
  LoginLayoutSignUpIndexRoute: LoginLayoutSignUpIndexRoute,
}

const LoginLayoutRouteRouteWithChildren =
  LoginLayoutRouteRoute._addFileChildren(LoginLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedLayoutRouteRoute: AuthedLayoutRouteRouteWithChildren,
  LoginLayoutRouteRoute: LoginLayoutRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
