/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginLayoutRouteRouteImport } from './routes/_loginLayout/route'
import { Route as AuthedLayoutRouteRouteImport } from './routes/_authedLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginLayoutSignUpIndexRouteImport } from './routes/_loginLayout/signUp/index'
import { Route as LoginLayoutFindPwIndexRouteImport } from './routes/_loginLayout/findPw/index'
import { Route as LoginLayoutFindIdIndexRouteImport } from './routes/_loginLayout/findId/index'
import { Route as AuthedLayoutOperationsIndexRouteImport } from './routes/_authedLayout/operations/index'
import { Route as AuthedLayoutMembersIndexRouteImport } from './routes/_authedLayout/members/index'
import { Route as AuthedLayoutHrIndexRouteImport } from './routes/_authedLayout/hr/index'
import { Route as AuthedLayoutFinanceIndexRouteImport } from './routes/_authedLayout/finance/index'
import { Route as AuthedLayoutConsultationsIndexRouteImport } from './routes/_authedLayout/consultations/index'
import { Route as AuthedLayoutClassesIndexRouteImport } from './routes/_authedLayout/classes/index'
import { Route as AuthedLayoutAdmissionsIndexRouteImport } from './routes/_authedLayout/admissions/index'
import { Route as AuthedLayoutAboutIndexRouteImport } from './routes/_authedLayout/about/index'

const LoginLayoutRouteRoute = LoginLayoutRouteRouteImport.update({
  id: '/_loginLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutRouteRoute = AuthedLayoutRouteRouteImport.update({
  id: '/_authedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLayoutSignUpIndexRoute = LoginLayoutSignUpIndexRouteImport.update({
  id: '/signUp/',
  path: '/signUp/',
  getParentRoute: () => LoginLayoutRouteRoute,
} as any)
const LoginLayoutFindPwIndexRoute = LoginLayoutFindPwIndexRouteImport.update({
  id: '/findPw/',
  path: '/findPw/',
  getParentRoute: () => LoginLayoutRouteRoute,
} as any)
const LoginLayoutFindIdIndexRoute = LoginLayoutFindIdIndexRouteImport.update({
  id: '/findId/',
  path: '/findId/',
  getParentRoute: () => LoginLayoutRouteRoute,
} as any)
const AuthedLayoutOperationsIndexRoute =
  AuthedLayoutOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutMembersIndexRoute =
  AuthedLayoutMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutHrIndexRoute = AuthedLayoutHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AuthedLayoutRouteRoute,
} as any)
const AuthedLayoutFinanceIndexRoute =
  AuthedLayoutFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutConsultationsIndexRoute =
  AuthedLayoutConsultationsIndexRouteImport.update({
    id: '/consultations/',
    path: '/consultations/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutClassesIndexRoute =
  AuthedLayoutClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutAdmissionsIndexRoute =
  AuthedLayoutAdmissionsIndexRouteImport.update({
    id: '/admissions/',
    path: '/admissions/',
    getParentRoute: () => AuthedLayoutRouteRoute,
  } as any)
const AuthedLayoutAboutIndexRoute = AuthedLayoutAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AuthedLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/about': typeof AuthedLayoutAboutIndexRoute
  '/admissions': typeof AuthedLayoutAdmissionsIndexRoute
  '/classes': typeof AuthedLayoutClassesIndexRoute
  '/consultations': typeof AuthedLayoutConsultationsIndexRoute
  '/finance': typeof AuthedLayoutFinanceIndexRoute
  '/hr': typeof AuthedLayoutHrIndexRoute
  '/members': typeof AuthedLayoutMembersIndexRoute
  '/operations': typeof AuthedLayoutOperationsIndexRoute
  '/findId': typeof LoginLayoutFindIdIndexRoute
  '/findPw': typeof LoginLayoutFindPwIndexRoute
  '/signUp': typeof LoginLayoutSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/about': typeof AuthedLayoutAboutIndexRoute
  '/admissions': typeof AuthedLayoutAdmissionsIndexRoute
  '/classes': typeof AuthedLayoutClassesIndexRoute
  '/consultations': typeof AuthedLayoutConsultationsIndexRoute
  '/finance': typeof AuthedLayoutFinanceIndexRoute
  '/hr': typeof AuthedLayoutHrIndexRoute
  '/members': typeof AuthedLayoutMembersIndexRoute
  '/operations': typeof AuthedLayoutOperationsIndexRoute
  '/findId': typeof LoginLayoutFindIdIndexRoute
  '/findPw': typeof LoginLayoutFindPwIndexRoute
  '/signUp': typeof LoginLayoutSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authedLayout': typeof AuthedLayoutRouteRouteWithChildren
  '/_loginLayout': typeof LoginLayoutRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authedLayout/about/': typeof AuthedLayoutAboutIndexRoute
  '/_authedLayout/admissions/': typeof AuthedLayoutAdmissionsIndexRoute
  '/_authedLayout/classes/': typeof AuthedLayoutClassesIndexRoute
  '/_authedLayout/consultations/': typeof AuthedLayoutConsultationsIndexRoute
  '/_authedLayout/finance/': typeof AuthedLayoutFinanceIndexRoute
  '/_authedLayout/hr/': typeof AuthedLayoutHrIndexRoute
  '/_authedLayout/members/': typeof AuthedLayoutMembersIndexRoute
  '/_authedLayout/operations/': typeof AuthedLayoutOperationsIndexRoute
  '/_loginLayout/findId/': typeof LoginLayoutFindIdIndexRoute
  '/_loginLayout/findPw/': typeof LoginLayoutFindPwIndexRoute
  '/_loginLayout/signUp/': typeof LoginLayoutSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/admissions'
    | '/classes'
    | '/consultations'
    | '/finance'
    | '/hr'
    | '/members'
    | '/operations'
    | '/findId'
    | '/findPw'
    | '/signUp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/about'
    | '/admissions'
    | '/classes'
    | '/consultations'
    | '/finance'
    | '/hr'
    | '/members'
    | '/operations'
    | '/findId'
    | '/findPw'
    | '/signUp'
  id:
    | '__root__'
    | '/'
    | '/_authedLayout'
    | '/_loginLayout'
    | '/login/'
    | '/_authedLayout/about/'
    | '/_authedLayout/admissions/'
    | '/_authedLayout/classes/'
    | '/_authedLayout/consultations/'
    | '/_authedLayout/finance/'
    | '/_authedLayout/hr/'
    | '/_authedLayout/members/'
    | '/_authedLayout/operations/'
    | '/_loginLayout/findId/'
    | '/_loginLayout/findPw/'
    | '/_loginLayout/signUp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedLayoutRouteRoute: typeof AuthedLayoutRouteRouteWithChildren
  LoginLayoutRouteRoute: typeof LoginLayoutRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_loginLayout': {
      id: '/_loginLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LoginLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authedLayout': {
      id: '/_authedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_loginLayout/signUp/': {
      id: '/_loginLayout/signUp/'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof LoginLayoutSignUpIndexRouteImport
      parentRoute: typeof LoginLayoutRouteRoute
    }
    '/_loginLayout/findPw/': {
      id: '/_loginLayout/findPw/'
      path: '/findPw'
      fullPath: '/findPw'
      preLoaderRoute: typeof LoginLayoutFindPwIndexRouteImport
      parentRoute: typeof LoginLayoutRouteRoute
    }
    '/_loginLayout/findId/': {
      id: '/_loginLayout/findId/'
      path: '/findId'
      fullPath: '/findId'
      preLoaderRoute: typeof LoginLayoutFindIdIndexRouteImport
      parentRoute: typeof LoginLayoutRouteRoute
    }
    '/_authedLayout/operations/': {
      id: '/_authedLayout/operations/'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthedLayoutOperationsIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/members/': {
      id: '/_authedLayout/members/'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedLayoutMembersIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/hr/': {
      id: '/_authedLayout/hr/'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthedLayoutHrIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/finance/': {
      id: '/_authedLayout/finance/'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthedLayoutFinanceIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/consultations/': {
      id: '/_authedLayout/consultations/'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AuthedLayoutConsultationsIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/classes/': {
      id: '/_authedLayout/classes/'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthedLayoutClassesIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/admissions/': {
      id: '/_authedLayout/admissions/'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AuthedLayoutAdmissionsIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
    '/_authedLayout/about/': {
      id: '/_authedLayout/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthedLayoutAboutIndexRouteImport
      parentRoute: typeof AuthedLayoutRouteRoute
    }
  }
}

interface AuthedLayoutRouteRouteChildren {
  AuthedLayoutAboutIndexRoute: typeof AuthedLayoutAboutIndexRoute
  AuthedLayoutAdmissionsIndexRoute: typeof AuthedLayoutAdmissionsIndexRoute
  AuthedLayoutClassesIndexRoute: typeof AuthedLayoutClassesIndexRoute
  AuthedLayoutConsultationsIndexRoute: typeof AuthedLayoutConsultationsIndexRoute
  AuthedLayoutFinanceIndexRoute: typeof AuthedLayoutFinanceIndexRoute
  AuthedLayoutHrIndexRoute: typeof AuthedLayoutHrIndexRoute
  AuthedLayoutMembersIndexRoute: typeof AuthedLayoutMembersIndexRoute
  AuthedLayoutOperationsIndexRoute: typeof AuthedLayoutOperationsIndexRoute
}

const AuthedLayoutRouteRouteChildren: AuthedLayoutRouteRouteChildren = {
  AuthedLayoutAboutIndexRoute: AuthedLayoutAboutIndexRoute,
  AuthedLayoutAdmissionsIndexRoute: AuthedLayoutAdmissionsIndexRoute,
  AuthedLayoutClassesIndexRoute: AuthedLayoutClassesIndexRoute,
  AuthedLayoutConsultationsIndexRoute: AuthedLayoutConsultationsIndexRoute,
  AuthedLayoutFinanceIndexRoute: AuthedLayoutFinanceIndexRoute,
  AuthedLayoutHrIndexRoute: AuthedLayoutHrIndexRoute,
  AuthedLayoutMembersIndexRoute: AuthedLayoutMembersIndexRoute,
  AuthedLayoutOperationsIndexRoute: AuthedLayoutOperationsIndexRoute,
}

const AuthedLayoutRouteRouteWithChildren =
  AuthedLayoutRouteRoute._addFileChildren(AuthedLayoutRouteRouteChildren)

interface LoginLayoutRouteRouteChildren {
  LoginLayoutFindIdIndexRoute: typeof LoginLayoutFindIdIndexRoute
  LoginLayoutFindPwIndexRoute: typeof LoginLayoutFindPwIndexRoute
  LoginLayoutSignUpIndexRoute: typeof LoginLayoutSignUpIndexRoute
}

const LoginLayoutRouteRouteChildren: LoginLayoutRouteRouteChildren = {
  LoginLayoutFindIdIndexRoute: LoginLayoutFindIdIndexRoute,
  LoginLayoutFindPwIndexRoute: LoginLayoutFindPwIndexRoute,
  LoginLayoutSignUpIndexRoute: LoginLayoutSignUpIndexRoute,
}

const LoginLayoutRouteRouteWithChildren =
  LoginLayoutRouteRoute._addFileChildren(LoginLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedLayoutRouteRoute: AuthedLayoutRouteRouteWithChildren,
  LoginLayoutRouteRoute: LoginLayoutRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
